#Sonic Pi: experimental way of incorporating cues in a stream of notes to generate harmony, by Robin Newman, April 2015
#The note stream and associated duration stream are sent to a function playstream. This filters out some very high values
#(notes higher than :c9  {note value 120} which are not going to be used in practice), and uses them to generate cues via a Ruby case statement
#Thus a note value of 121 generates cue :trig1, 122 => cue :trig2 etc up to 130 => cue :trig9
#To make it easy a function tc generates the number for you thus tc(1) => 129....tc(9) => 130
#Calls to the function tc are inserted in teh note stream, with a corresponding duration value 0 into the duration stream, so they take
#up negligible time. The triggers can be used to release live_loops which can generate secondary harmony notes synced to the original stream
#The example has three alternative streams chosen at random, each with their own harmony live loops.
#The duration of the notes in the streams are chosen at random, but because of way teh harmonies are generated by cued triggers the
#whole thing hangs together and the end result is a nice little repeating harmonious jingle.

#The jingle fadesin and then out again after 1 minute. You still have to press stop after this, but it ends it in a nice manner.

use_synth_defaults release: 0.8 #applies to harmony loops b-g
max=60 #time before fade out in seconds (min value 10)

define :tc do |n| #returns note number for trigger n
  return n+120
end

define :playstring do |ns,ds| #plays stream of notes and durations and parses it for cue triggers
  ns.zip(ds) do |n,d| #loop through the linked note and uration lists
    if note(n) > 120 #if the "note" value exceeds 120 it is a trigger
      case note(n)-120 #use a case statement to select the appropriate trigger to cue
      when 1
        cue :trig1
      when 2
        cue :trig2
      when 3
        cue :trig3
      when 4
        cue :trig4
      when 5
        cue :trig5
      when 6
        cue :trig6
      when 7
        cue :trig7
      when 8
        cue :trig8
      when 9
        cue :trig9
      end
    else #otherwise it is a "normal" note so play it
      play n,sustain: d*0.9,release: d*0.1,amp: 0.7
      sleep d #sleep for note duration
    end
  end
end

with_fx :reverb, room: 0.6 do #add some reverb
  with_fx :level do |amp| #level control allows for fade in and out
    control amp,amp:  0 #set initial level value

    live_loop :conduct do |c| #does fade in and fade out after time specified by max variable
      if c < 11
        control amp,amp: c.to_f/10 #does the fade in on the fisrt 10 passes of the loop
      end
      if c == max+11 #checks if the end fade has finished and if so stops this loop
        x=1/0 #replace with stop if you have ver 2.6dev or later: otherwise this existing code generates an error and stops this loop
      end
      if c >= max #checks if time for final fade
      then
        sync :a #sync fades with start of main loop
        control amp,amp: (1 - (c-max).to_f/10) #do next fade step
      end
     #puts c #for debugging purposes
      sleep 1
      c +=1 #bump the loop counter
    end


    live_loop :a do #the main loop which selects and plays one of the three note streams at random on each pass
      use_synth :tri #synth for note stream part
      sleep 0.05 #Allows levl change to complete before next note plays. Otherwise glitch when piece ends
      n1=[tc(1),tc(2),:c4,:d4,:e4,:f4,tc(3),:g4,:a4,:b4,:c5] #note stream1 with cue triggers inserted
      n2=[tc(4),tc(5),:f3,:g3,:a3,:b3,tc(6),:c4,:d4,:e4,:f4] #note stream2 with differnt cue triggers
      n3=[tc(7),tc(8),:g3,:a3,:b3,:c4,tc(9),:d4,:e4,:f4,:g3] #note stream3, again with differnt triggers
      x = [0.1,0.1,0.2,0.2,0.2,0.3,0.4].choose
      d=[0,0,x,x,x,x,0,x,x,x,x] #common duration string with 0 inserted corrseponding to trigger locations
      playstring([n1,n2,n3].choose,d) #choose and play 1 note stream
    end

    live_loop :b do #loop that deals with triggers 1 and 3

      sync :trig1
      play :c4
      sync :trig3
      play :c5
      sleep 0.2
    end

    live_loop :c do #loop deals with trigger 2

      sync :trig2
      play [:c5,:e5,:g5]
      sleep 0.2
    end

    live_loop :d do #loop deals with triggers 4 and 6

      sync :trig4
      play :f4
      sync :trig6
      play :f5
      sleep 0.2
    end

    live_loop :e do #loop deals with trigger 5

      sync :trig5
      play [:c5,:f5,:a5]
      sleep 0.2
    end

    live_loop :f do #loop deals with triggers 7 and 9

      sync :trig7
      play :g3
      sync :trig9
      play :g4
      sleep 0.2
    end

    live_loop :g do #loop deals with trigger 8

      sync :trig8
      play [:b4,:d5,:g5]
      sleep 0.2
    end
  end
end