#!/usr/bin/env python3
#OSCglockenspiel.py written by Robin Newman, May 2018 
#program sets up an OSC server and receives OSC messages sent to "/note"
#Sonic Pi can be running either on the Raspberry Pi (default),
#or on an external networked computer

#All of the libraries required should be standard on the latest Raspbian apart from pythonosc
#To install this use sudo pip3 install python-osc


from gpiozero import LEDBoard
from pythonosc import udp_client
from pythonosc import dispatcher
from pythonosc import osc_server
from time import sleep
import argparse
import sys

leds=LEDBoard(9,10,11,12,13,14,15,16,17,18,19) #pins connected to ULM2803A driver or TIP120 power transistors
#via GPIO pins 9-19
  
 #This is activated when /note OSC message is received by the server.
 #the arguments n represents the note position in the LEDBoard array 0->9  
def pulse(unused_addr,args,m): #pulse pin corresponding to received number for 0.05 seconds
    print("note",m)
    leds[m].on()
    sleep(0.05)
    leds[m].off()      

#The main routine called when the program starts up follows
if __name__ == "__main__":
    try: #use try...except to handle possible errors
        #first set up and deal with input args when program starts
        parser = argparse.ArgumentParser()
        #This arg gets the server IP address to use. 127.0.0.1 or
        #The local IP address of the PI, required when using external Sonic Pi
        parser.add_argument("--ip",
        default="127.0.0.1", help="The ip to listen on")
        #This is the port on which the server listens. Usually 8000 is OK
        #but you can specify a different one
        parser.add_argument("--port",
              type=int, default=8000, help="The port to listen on")
        #This is the port used for the connection, you can change it if you wissh,
        #but the default port 8000 should be OK.
        args=parser.parse_args()
        dispatcher = dispatcher.Dispatcher()
        #following dispatcher handles /note osc messages being received
        dispatcher.map("/note",pulse,"n")
        #Now set up and run the OSC server
        server = osc_server.ThreadingOSCUDPServer(
              (args.ip, args.port), dispatcher)
        print("Serving on {}".format(server.server_address))
        #run the server "forever" (till stopped by pressing ctrl-C)
        server.serve_forever()
    #deal with some error events
    except KeyboardInterrupt:
        print("\nServer stopped") #stop program with ctrl+C
    #Used the AttributeError to specify problems with the local ip address
    except AttributeError as err:
        print(err.args[0])
    #handle errors generated by the server
    except OSError as err:
       print("OSC server error",err.args)
    #anything else falls through